title: Yuxuan Sun
description: The personal academic homepage of Yuxuan Sun
author: Yuxuan Sun
avatar: /logo.png
email: yuxuans@smu.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

lang: en
